#!/bin/sh

sxhkd &

# bspc config bottom_padding        50
bspc config border_width            1
bspc config focused_border_color    \#ffb52a
bspc config normal_border_color     \#555555
bspc config window_gap              10

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true
bspc config history_aware_focus     true

bspc monitor -d Term Web Dev SSH

bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a Firefox desktop=^2 follow=on border=off
bspc rule -a qutebrowser desktop=^2 follow=on border=off
bspc rule -a Lxappearance state=floating center=true

xsetroot -cursor_name left_ptr &
compton &
feh --bg-scale ~/Pictures/Wallpapers/Horror/the_dark_ages_by_jonasdero-d55wvrb.jpg &
~/Projects/polybar/build/bin/polybar topbar &
sleep 1; dunst -config /home/chris/.i3/dunst.conf &
sleep 1; xfce4-power-manager &
udiskie --tray &
nm-applet &
volumeicon &
